### ISSUE TITLE
Blank screen in VR

### ISSUE THREAD

**Issue by fucnknown** [MichaelJW/DorsalVR#10]
Greetings, trying to use this fantastic project. 
Regrettably I've been unable to have Dorsal opening Dolphin so far.

- Configuration looks almost the same than what's posted in the wiki (just changing the username and Dolphin's folder, obviously).-
- Dolphin runs standalone and it runs roms.-

Dorsal runs and stays open, I'm in a bluish room with a white screen:  [screenshot](https://imgur.com/a/CmaolMM) .- 
Nothing is running either on the computer desktops or within that screen,- 
Checked the tasks running to see if the Dolphin process was there, no luck.-

Player log at [pastebin](https://pastebin.com/0YKeh3Na)

HMD is Valve Index, card NVIDIA 1080ti

Don't know what else to provide, regards

**Comment by MichaelJW** [comment]
Hey @fnowicky, thanks for the details and the log. I'm away from my main computer at the moment so I can't dig into this, but in the meantime could you send me your default.yaml file and any other YAML files you've created please? Thanks!

**Comment by fucnknown** [comment]
Hi @MichaelJW , as I said, the file looks almost exactly like the one in the wiki, here you have its contents - [pastebin](https://pastebin.com/daLRJNZg).
I have not created other files, I **did** attempt to copy the content from the imports in "GameCubeExample.yaml" and merge everything in the default, removing the import, that didn't work either, same outcome.

I have experience with YAML files from minecraft server configs, the project seems to use 2-spaces yaml, correct?
Just to be sure that the system is able to load the configuration.

Regards,

**Comment by MichaelJW** [comment]
Hey @fnowicky, your YAML is fine and it can be loaded. 

It looks like DorsalVR is starting up, attempting to capture and mirror your primary desktop (by default), failing, and then therefore never getting to the point where it loads Dolphin and mirrors that instead.

In a future build I'll make it deal more gracefully with not being able to capture the primary desktop - it should give an error message or at least not stop Dolphin from loading. 

In the meantime, could you possibly try changing your primary desktop? 

Also, do you have two GPUs set up, perhaps an integrated one alongside your 1080ti? If so, try the "For Windows 10 1909 or newer" instructions [here](https://obsproject.com/forum/threads/laptop-black-screen-when-capturing-read-here-first.5965/), except select `DorsalVR.exe` rather than `obs64.exe`, then load DorsalVR again. (This might make the performance absolutely terrible but it will at least help to narrow down the problem.)

Thanks!

**Comment by fucnknown** [comment]
Hi @MichaelJW , this is a Desktop computer with a single NVIDIA 1080 ti (ftw). I **do** have 2 desktops normally. as a side comment I normally use OBS to capture without issues as well as zoom and other screen sharing software.-

I disabled and completely disconnected the secondary monitor as a test. No good. [Logs attached](https://pastebin.com/mSSUQHKF)


I found it odd that you directed me to version 1909 instructions, I'm running version [1809 Windows LTSC](https://i.imgur.com/evNtcXP.png).- Does Dorsal require some odd feature from standard windows? (This would be a first for me, since I've been using this version for gaming since it came out). Did you specify 1909 because the log told you that was my version?

Here are a couple of screenshots of my NVIDIA settings (what OBS intructions would indicate for my version. [PhysX from before completely disconnecting the 2nd monitor](https://i.imgur.com/OBvTm6X.png) and [Dorsal settings in NVIDIA](https://i.imgur.com/01felMK.png), you'll notice that there are no options to choose another card,

Tell me any tests you might wanna try.

PS: Just for the sake of completion I found the setting mentioned and specifically [added Dorsal with the only card available](https://i.imgur.com/CAIHvgd.png). I even run Dorsal as Admin, no dice, [logs attached](https://pastebin.com/eQhS5NKJ)

PS2: Just FYI I work as sysadmin, and have a long experience with computers, I even worked as programmer.- Though all this Unity and calculations needed for 3D graphics scape me beyond the theoretical. feel free to shoot things directly

**Comment by MichaelJW** [comment]
@fnowicky Ah! Well that explains it - [looks like the ability to capture a monitor was introduced in the May 2019 update](https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture/) (1903), so I bet that's why it's failing there. (I didn't know which version you were on so I just guessed the latest.) 

Next chance I get, I'll put some more logging and a more graceful fail around the part that attempts to capture a monitor and we'll see if that sorts it 🙂

**Comment by fucnknown** [comment]
Oof, Then I'll have to wait till LTSC 21H2, since I refuse to use the standard versions. (I very much prefer the stability of the Server intended versions, also the lack of ads/adware)      
Just as a question, since I'm able to use all manner of screen capture software and VR desktop solutions, would you consider using another method for capture or is there a technical reason for the one you are using? (no pressure, just curious)

Glad we were able to find the reason though.

**Comment by MichaelJW** [comment]
@fnowicky I'm sorry about that :(

> Just as a question, since I'm able to use all manner of screen capture software and VR desktop solutions, would you consider using another method for capture or is there a technical reason for the one you are using?

**Comment by MichaelJW** [comment]
@fnowicky I'm sorry about that :(

> Just as a question, since I'm able to use all manner of screen capture software and VR desktop solutions, would you consider using another method for capture or is there a technical reason for the one you are using?

I did used to use the older [Desktop Duplication API](https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api), but that's much blunter - it only lets you capture an entire display, while the Windows Graphics Capture API lets you capture a specific window.

The limitation of the WGC API, pre-1903, is that the app has to use a built in system dialog to ask the user which monitor or window to capture; presumably that's what other screen capture software does, if they don't roll their own solution.

![Example of the built in GraphicsCapturePicker system dialog](https://user-images.githubusercontent.com/136441/128638435-51d0d16f-94ca-4cd4-ae31-44c885b38cd2.png)

It might be possible to use this dialog in DorsalVR but I'm not sure whether it will work in Unity. I'll put it on my list of things to check out, though 📝

**Comment by fucnknown** [comment]
Thank you I'll keep watching the Project, and test it once LTSC 21H2 arrives or if you make any changes. I'll close the bug report. Good luck and keep up the good work!
